keto = ["Fuck Gordo",
         "Gordo is open-sourced malware",
         "I need paper",
         "Castyte is a fucking communist",
         "Send paper",
         "gm school's out", 
         "I need paper stfu everyone", 
         "sorry im dyslexic", 
         "No I need paper", 
         "Hey, I can't upvote with reactions", 
         "Nigga ported APT to Mac and thinks he's god smh", 
         "Nepcord was better", 
         "I miss Nepcord", 
         "Only real men listen to *Love You Like A Love Song*", 
         "*I, I love you like a love song, baby. I, I love you like a love song, baby. I, I love you like a love song, baby. And I keep hit in re-pe-pe-peat*", 
         "I swear I'm not suicidal or nothing but like when tf did Ariana Grande become famous? ? ?",
         "petition for toilet repo to get own original unique homepage", 
         "Imagine having to jailbreak through a wire",
         ";",
         "Sorry for not confirming my gender, OG",
         "stop flexing on others its the most shit thing you can do this is why no one loves you now stfu",
         "y'all motherfuckers deadass ganging up on me",
         "shut the fuck up u fat ill bread boy",
         "please stop askingme to the nword", 
         "you guys are literally the gayest human beings alive", 
         "yea im so funny omg lemme react with furry emote ahahhaahaha its keto burh", 
         "please use sass next time you shitty ass cat", "KetoBot will be triggered by doing ;nigga", 
         "JUST USE APT DPKG AND TERMINAL AND STFU NIGGAS", 
         "just fucking say sorry nigga faggot", 
         "i cant even react nigga", 
         "stfu go to sleep and refrain from waking up tomorrow faggot", 
         "futurerestore is obsolete stfu", 
         "my futurerestore guide is outdated again", 
         "anyone here have a linux version of futurerestore", 
         "whoever has a fork of futurerestoreguide.md please delete", 
         "Too many fucking forks of Android. Not ideal", 
         "if you have a copy of futurerestoreguide.md please delete it", 
         "im  sad fuck futurerestoreguide.md", 
         "imagine a package manager draining battery LMAO", 
         "gordo said castyte was gay", 
         "toilet repo gaY /s",
         "just fucking unmute me and go jerk off",
         "fuck 7-zip",
         "someone please tell me how to stop altstore from crashing",
         "bruh all my quotes areunder gpl-3",
         "im done with this gay bot",
         "haha its funny to see keto angry LMAO",
         "i seriously wish this bot was taken down of github",
         "and i cant leave this place because i wont be able to rejoin"]


human = ["I don’t wanna give myself dev role because that’s gonna just make me sad", 
         "I would fuck coolstar for free", 
         "fuck discord", 
         "can we please move to keybase", 
         "castyte is gay", 
         "Delete", 
         "imagine liking image compression", 
         "screenshotter plus plus by nigga inc for android", 
         "home depot", 
         "more saving more doing", 
         "black cockburger", 
         "please keep gay shit in <#642863820733153290>", 
         "furry =/ lgbtq", 
         "Thank you keto, very cool!", 
         "electra bootlooped my xs max help",
         "do you know what a pull request is, nigga?",
         "Keto~~Bot~~ will be triggered ~~by doing ;nigga~~",
         "jumping on saurik’s cock"]


gaynasa = ["bruh wtf is non binary what are u hexadecimal?",
          "imagine using a keyboard layout that isnt qwertyuiop",
          "furries don't have dicks they have micro penis dipped in gay cum",
          "I'm An Alabama gamer and I want to be free",
          "Phat Ass White Girls DM Me",
          "niggas has extra chromosomes",
          "just scratched my balls"]

gordo =  ["Can we warn this guy ?",
         "DDLC-IOS > ShortLook",
         "Kanye is the most influencial artist of our generation !",
         "Link of BetterDiscord Windows",
         "im going to sleep 1 more hour. Dont wake me up",
         "how is this allowed in here?",
         "I hate that Dieter guys",
         "<@585955457781202964> Who are you ?"]

rams =   ["Big dicks make me feel like I'm gagging but from my rectum instead of my throat",
          "gay",
          "Well a13 gay",
          "imagine thinking that I’m actually gay",
          "my ass isn’t an entry",
          "Stfu this isn’t gay bot",
          "can I succ ur gfs dick",
          "Bussy",
          "don’t fuck cydia, fuck me instead!",
          "Upvote if you fucked yourself with your own dick",
          "We don’t race cysts here",
          "too bad nepcord was deleted otherwise you would have gotten fag level quotes",
          "canceling your free succ credits",
          "petition to bring back #gordonudes"]
        